### ISSUE TITLE
NodeRed Getting Multiple Repeated Messages From Nodes

### ISSUE THREAD

**Issue by Ryonez** [Skylar-Tech/node-red-contrib-matrix-chat#36]
This is an odd one.

It seems that nodes will duplicate messages, and that can snowball down the line.

I'm looking at one message getting 4 triggers on a `Receive` node then 9 from the `Room User List` it's linked to.

It's not wholly consistent either.

Trigger messages (and response to the one set to respond):
![image](https://user-images.githubusercontent.com/16157130/146550188-48c60f0d-4b1b-4c46-9c4e-b84ab3ce716e.png)

The Flows:
![image](https://user-images.githubusercontent.com/16157130/146550420-b6757646-0c68-4e18-86ef-447c21235a7f.png)

<details><summary>Flow Code:</summary><p>

```json
[
    {
        "id": "af9a42c4da8726ea",
        "type": "matrix-receive",
        "z": "60339a6fa3ae56a7",
        "name": "Ping",
        "server": "",
        "roomId": "",
        "acceptText": true,
        "acceptEmotes": true,
        "acceptStickers": true,
        "acceptReactions": true,
        "acceptFiles": true,
        "acceptImages": true,
        "x": 100,
        "y": 1012,
        "wires": [
            [
                "e4b73d13036940f6"
            ]
        ]
    },
    {
        "id": "d083f1b20f40f726",
        "type": "matrix-receive",
        "z": "60339a6fa3ae56a7",
        "name": "Other Testing",
        "server": "",
        "roomId": "",
        "acceptText": true,
        "acceptEmotes": true,
        "acceptStickers": true,
        "acceptReactions": true,
        "acceptFiles": true,
        "acceptImages": true,
        "x": 109.5,
        "y": 811,
        "wires": [
            [
                "606970b0770ab888",
                "7502f29121a84165"
            ]
        ]
    },
    {
        "id": "606970b0770ab888",
        "type": "switch",
        "z": "60339a6fa3ae56a7",
        "name": "Command Function",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "s-users",
                "vt": "str"
            },
            {
                "t": "eq",
                "v": "r-users",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 296.5,
        "y": 811,
        "wires": [
            [
                "b4dfcb88a9bd1a61"
            ],
            [
                "4a22dfa44a915d68",
                "50ce404dd5d819ae"
            ]
        ]
    },
    {
        "id": "b4dfcb88a9bd1a61",
        "type": "matrix-synapse-users",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "server": "",
        "x": 570.5,
        "y": 775,
        "wires": [
            [
                "5be3f7b22cbab39e",
                "2e795181cbdd92a9"
            ],
            []
        ]
    },
    {
        "id": "a2bf7ff592d05ce1",
        "type": "matrix-send-message",
        "z": "60339a6fa3ae56a7",
        "name": "Send HTML Notice",
        "server": "",
        "roomId": "",
        "messageType": "m.notice",
        "messageFormat": "html",
        "x": 952.5,
        "y": 806,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "5be3f7b22cbab39e",
        "type": "function",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "func": "let new_payload = '<ul>';\nmsg.payload.users.forEach(function(user, index){\n    new_payload += '<li>'+ JSON.stringify(user, null, 2).replace(/(?:\\r\\n|\\r|\\n)/g, \"\\n<br>\"); + '</li>'\n});\nmsg.payload = new_payload + '</ul>';\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 829.5,
        "y": 754,
        "wires": [
            [
                "a2bf7ff592d05ce1"
            ]
        ]
    },
    {
        "id": "f813ce2610c98750",
        "type": "comment",
        "z": "60339a6fa3ae56a7",
        "name": "Response to \"s-users\" with full server user list",
        "info": "",
        "x": 557.5,
        "y": 720,
        "wires": []
    },
    {
        "id": "0c27f5356d7e856b",
        "type": "comment",
        "z": "60339a6fa3ae56a7",
        "name": "Response to \"r-users\" with room user list",
        "info": "",
        "x": 569.5,
        "y": 893,
        "wires": []
    },
    {
        "id": "4a22dfa44a915d68",
        "type": "matrix-room-users",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "server": "",
        "roomId": "",
        "x": 558,
        "y": 834,
        "wires": [
            [
                "2e795181cbdd92a9"
            ],
            []
        ]
    },
    {
        "id": "e4b73d13036940f6",
        "type": "switch",
        "z": "60339a6fa3ae56a7",
        "name": "msg.payload == \"ping\"",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "ping",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 1,
        "x": 325.5,
        "y": 1020,
        "wires": [
            [
                "4214bb4d742d8d5b"
            ]
        ]
    },
    {
        "id": "7940da0c776d33dc",
        "type": "matrix-send-message",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "server": "",
        "roomId": "",
        "messageType": "m.text",
        "messageFormat": "",
        "x": 725,
        "y": 1015,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "4214bb4d742d8d5b",
        "type": "function",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "func": "msg.payload = \"pong\"\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 535,
        "y": 1013,
        "wires": [
            [
                "78d47c18f303939e",
                "7940da0c776d33dc"
            ]
        ]
    },
    {
        "id": "78d47c18f303939e",
        "type": "debug",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 684,
        "y": 1103,
        "wires": []
    },
    {
        "id": "2e795181cbdd92a9",
        "type": "debug",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 853,
        "y": 876,
        "wires": []
    },
    {
        "id": "7502f29121a84165",
        "type": "debug",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 159,
        "y": 912,
        "wires": []
    },
    {
        "id": "50ce404dd5d819ae",
        "type": "debug",
        "z": "60339a6fa3ae56a7",
        "name": "",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 475,
        "y": 941,
        "wires": []
    }
]
```
</p></details>

The debug log for these three debug nodes (The log was cleared for this test, note the scrollbar):
![image](https://user-images.githubusercontent.com/16157130/146551401-2bd86b9c-0184-44f9-b14f-91c08eb82b3e.png)

**Comment by skylord123** [comment]
I was able to replicate the issue finally. I got a new release coming out today that should fix this. Thanks for the input!

**Comment by skylord123** [comment]
Just released `0.3.0` that fixes this problem. I will close this for now, if you still have the problem feel free to re-open the issue.

**Comment by Ryonez** [comment]
@skylord123 It's not normally possible for users to reopen issues. I cannot in this case for example. I'd like to suggest that issues are left open to give some time to get feedback on if it's actually been resolved.

In this case it seem not to have been sadly, It's seeing a message more than once, and I'm still getting multiple responses.

![image](https://user-images.githubusercontent.com/16157130/149605336-0010ca8e-6498-4afd-883d-8a66d106e74b.png)

![image](https://user-images.githubusercontent.com/16157130/149605352-a769be68-10ea-42b6-93a9-ab47228554fa.png)

**Comment by skylord123** [comment]
@Ryonez Can you do another test and paste the log output here? I'm wondering if they are duplicating in the log as well.

**Comment by Ryonez** [comment]
Yup, they are dupped in the logs to.

<details><summary>Relevent Logs:</summary><p>
```
setting pendingEvent status to sending in !BCwBSIvaRXQCucvPCQ:alteria.xyz event ID ~!BCwBSIvaRXQCucvPCQ:alteria.xyz:m1643399173986.6 -> undefined
setting pendingEvent status to queued in !BCwBSIvaRXQCucvPCQ:alteria.xyz event ID ~!BCwBSIvaRXQCucvPCQ:alteria.xyz:m1643399173986.6 -> undefined
Event sent to !BCwBSIvaRXQCucvPCQ:alteria.xyz with event id $svZ9mch58RR9nlU7irl3IsBxnTnKO6DfyxZYI8lo2H4
setting pendingEvent status to sent in !BCwBSIvaRXQCucvPCQ:alteria.xyz event ID ~!BCwBSIvaRXQCucvPCQ:alteria.xyz:m1643399173954.4 -> $svZ9mch58RR9nlU7irl3IsBxnTnKO6DfyxZYI8lo2H4
setting pendingEvent status to sending in !BCwBSIvaRXQCucvPCQ:alteria.xyz event ID ~!BCwBSIvaRXQCucvPCQ:alteria.xyz:m1643399173971.5 -> undefined
29 Jan 08:46:14 - [info] [matrix-send-message:34aced6aba4130b4] Message sent: pong
Got remote echo for event $svZ9mch58RR9nlU7irl3IsBxnTnKO6DfyxZYI8lo2H4 -> $svZ9mch58RR9nlU7irl3IsBxnTnKO6DfyxZYI8lo2H4 old status sent
29 Jan 08:46:14 - [info] [matrix-server-config:nodered-matrix] Received encrypted timeline event [m.text]: (Other Testing) @yoko:alteria.xyz :: pong [LIVE]
Event sent to !BCwBSIvaRXQCucvPCQ:alteria.xyz with event id $7qWRFC2vGuK1gbfpI6sSRs4gUnx-ZNM9baCZOR85lko
setting pendingEvent status to sent in !BCwBSIvaRXQCucvPCQ:alteria.xyz event ID ~!BCwBSIvaRXQCucvPCQ:alteria.xyz:m1643399173971.5 -> $7qWRFC2vGuK1gbfpI6sSRs4gUnx-ZNM9baCZOR85lko
setting pendingEvent status to sending in !BCwBSIvaRXQCucvPCQ:alteria.xyz event ID ~!BCwBSIvaRXQCucvPCQ:alteria.xyz:m1643399173986.6 -> undefined
29 Jan 08:46:14 - [info] [matrix-send-message:34aced6aba4130b4] Message sent: pong
Got remote echo for event $7qWRFC2vGuK1gbfpI6sSRs4gUnx-ZNM9baCZOR85lko -> $7qWRFC2vGuK1gbfpI6sSRs4gUnx-ZNM9baCZOR85lko old status sent
29 Jan 08:46:14 - [info] [matrix-server-config:nodered-matrix] Received encrypted timeline event [m.text]: (Other Testing) @yoko:alteria.xyz :: pong [LIVE]
Event sent to !BCwBSIvaRXQCucvPCQ:alteria.xyz with event id $A8Fxr6vp5m9RPaTvFYzqe6ACwtWGeT5S05lKxKgYS8E
setting pendingEvent status to sent in !BCwBSIvaRXQCucvPCQ:alteria.xyz event ID ~!BCwBSIvaRXQCucvPCQ:alteria.xyz:m1643399173986.6 -> $A8Fxr6vp5m9RPaTvFYzqe6ACwtWGeT5S05lKxKgYS8E
29 Jan 08:46:14 - [info] [matrix-send-message:34aced6aba4130b4] Message sent: pong
Got remote echo for event $A8Fxr6vp5m9RPaTvFYzqe6ACwtWGeT5S05lKxKgYS8E -> $A8Fxr6vp5m9RPaTvFYzqe6ACwtWGeT5S05lKxKgYS8E old status sent
29 Jan 08:46:14 - [info] [matrix-server-config:nodered-matrix] Received encrypted timeline event [m.text]: (Other Testing) @yoko:alteria.xyz :: pong [LIVE]
```
</p></details>

**Comment by hillbicks** [comment]
I can report the same thing. As a workaround, I'm using the delay before the sending with action set to rate limit. This way I can limit the notifications to 1 message per 5 seconds for example.

**Comment by skylord123** [comment]
@hillbicks @Ryonez Can you both give me the following details to help diagnose this:

- What operating system are you running?
- How did you install Node-RED (in Docker, using apt, manually with NPM, etc)?
- What other modules have you installed in Node-RED?
- What matrix server are you using? (if this is self hosted you can just say that but if it's a public server list which server)
- If you self-host list which version of Synapse you are using
- What version is your Node-RED instance?
- Does this happen in both encrypted and non-encrypted rooms?

I haven't had much success in replicating this issue so I hope the above fixes that. 

Thanks :)

**Comment by Ryonez** [comment]
> * What operating system are you running Node-RED on?

unRaid 6.9.2

> * How did you install Node-RED (in Docker, using apt, manually with NPM, etc)?

Docker

> * What other modules have you installed in Node-RED?

        "@kuehnelbs/node-red-contrib-nextcloud": "~0.1.3",
        "@node-red-contrib-themes/midnight-red": "^1.4.7",
        "json-db-node-red": "~0.5.3",
        "node-red-contrib-basicauth": "~1.0.4",
        "node-red-contrib-bigssh": "~1.2.7",
        "node-red-contrib-discord-advanced": "~3.1.1",
        "node-red-contrib-google": "~0.2.0",
        "node-red-contrib-image-tools": "~2.0.2",
        "node-red-contrib-influxdb": "~0.6.1",
        "node-red-contrib-matrix-chat": "~0.3.0",
        "node-red-contrib-otpauth": "0.0.2",
        "node-red-contrib-plex-ws": "~0.2.4",
        "node-red-contrib-postgres-multi": "~0.2.0",
        "node-red-contrib-spotify": "~0.1.4",
        "node-red-contrib-telegrambot": "~11.2.0",
        "node-red-contrib-twitter-stream": "~1.5.0",
        "node-red-contrib-ui-media": "~1.2.0",
        "node-red-contrib-uibuilder": "~4.1.4",
        "node-red-contrib-uuid": "0.0.4",
        "node-red-dashboard": "~3.1.5",
        "node-red-node-email": "~1.14.0",
        "node-red-node-mongodb": "~0.2.5",
        "node-red-node-mysql": "~1.0.0",
        "node-red-node-rbe": "~0.5.0",
        "node-red-node-sentiment": "~0.1.6",
        "node-red-node-tail": "~0.3.2",
        "passport-keycloak-oauth2-oidc": "^1.0.5"
        
> * What Matrix server are you using? (if this is self hosted you can just say that but if it's a public server list which server)
`alteria.xyz`

> * If you self-host list which version of Synapse you are using

matrixdotorg/synapse:latest
Current hash: sha256:1776cc2e846d208d62206e81936a10c07f3fdb43c7262b28090dfc0e3bb4d4a9

> * What version is your Node-RED instance?

Node-RED v2.2.0
nodered/node-red:latest-16
Current hash: sha256:28baf510bc5e9ff0e29e34892aa7423a59b29050d8946ffc6e4be354827accab


> * Does this happen in both encrypted and non-encrypted rooms?

Both



Also, it seems to take a bit to trigger at time. When testing today, moving nodes and deploying the flow wasn't enough. I had to disable a debug node, save, reenable it, save again, then the message started repeating.
I normally have this flow disabled atm, and nodered has been restarted since I last looked at this. The Flow starts of fine, but as changes are made it starts having the problems.

**Comment by skylord123** [comment]
> If you need further information from my side, just let me know. Happy to help.

Can you start Node-RED, reproduce the issue, then send me the full log? You can send it over matrix to @skylord123:skylar.tech or to my email me@skylar.tech

@Ryonez can you do the same? Your log output above is missing the part where it shows the `ping` message coming in. It's also possible that during initializing the node is throwing an error so the full log would be helpful.

Before doing the test I would set logging to `debug` in your `settings.js` file. Information about how to do this can be found here:
https://nodered.org/docs/user-guide/runtime/logging

At first I thought it may have been another module causing the problem. I know that `nodered-contrib-signal-client` currently uses an old version of `proxy-agent` that causes problems (I opened an issue [here](https://github.com/gausma/nodered-contrib-signal-client/issues/36) that describes that problem). I don't think another package is causing the problem in this case though. @Ryonez It may be good for you to try spinning up a second node-red container and only installing `node-red-contrib-matrix-chat` and see if the problem still happens (just as a sanity check so we can rule out other packages being the culprit and since you run in Docker it is super easy to spin up another instance).

Thanks!

**Comment by hillbicks** [comment]
I.......ehm, should've looked at the logfile earlier it seems. 1.1GB in size :p  

I just saw a ton of errors in the logfile about errors uploading keys and broken secure channels. The thing is, I'm pretty sure I only changed the server names in node-red after I reinstalled synapse. 

So, let me clear that up first, I'll probably delete the complete matrix configuration again and set it up from scratch, I only have a couple of nodes at the moment. I'll let you know once I've done that. 

Sorry, should've checked that earlier!

**Comment by hillbicks** [comment]
So, after a lot of cleaning up (and one new minor issue that I discovered and reported (#46), I wanted to dig into this again. I deleted the pm2 logfile, restarted nodered.....and I can't reproduce it anymore. I also removed some palettes that I wasn't using anymore and currently this issue is gone. 

I'll try again later and give some feedback, just to let you know I haven't forgotten about this ;)

**Comment by skylord123** [comment]
@hillbicks which modules did you remove? It's entirely possible one of those was causing the problem.You can view the list you had above before you removed them for reference.

**Comment by hillbicks** [comment]
node-red-contrib-image-tools
node-red-contrib-mpd
node-red-node-xmpp

I removed these 3.

 I also added a node that responds to any message with a pong, so far it is sending only one pong.

**Comment by hillbicks** [comment]
@Ryonez Do you still experience this problem? Since my last report I never had another duplicate message. Not sure what the issue exactly was on my side, I also updated synapse as well as removing the the aforementioned addons from node red. 

So it seems to solved, at least for me.

**Comment by Ryonez** [comment]
Alright, set up another node red instance. This one doesn't have issues with multiple pings, even if I install `node-red-contrib-image-tools`.

That package though is used in my main nodered instance, removal isn't really an option, and I'm not convinced it's an issue as I can't replicate the issue in the new instance of nodered.

I don't have logs ready atm, I don't quite have the energy to go through them right now.

**Comment by Merikei** [comment]
Think I'm having the same issue

It happens when I modify a sequence containing a receive node and then 'deploy modified flows'.
My assumption is that this keeps the old connection to Matrix AND creates a new connection.
The Matrix nodes in the modified sequence displays a node status of 'disconnected' while unmodified sequences say connected. (It isn't actually disconnected.)
It happens some times and not others so it may be more complex than just modifying the sequence in any way.

Doing a 'deploy full' avoids the issue or fixes it but is itself a problem because it stops everything.

Thanks for this project by the way! :smiley:

**Comment by Merikei** [comment]
Messing around with enabling and disabling a receive node and connected debug node and 'deploy modified flows'. It's now outputting messages several times while other receive nodes are only outputting the same message once.

**Comment by skylord123** [comment]
> Messing around with enabling and disabling a receive node and connected debug node and 'deploy modified flows'. It's now outputting messages several times while other receive nodes are only outputting the same message once.

Can you check the time on the device you are running Node-RED on? Every time nodes are deployed or NR starts we save the initialized time and only send out messages that are newer than that. If the time on the device is incorrect (even off by some seconds) this could cause messages to reappear since it thinks they are new.

That would only happen on deploy/starting NR though and wouldn't duplicate messages after that. If you have messages being duplicated when not deploying/starting NR there is a good chance that another module you have installed is messing with the requests and I would try spinning up another NR instance without any other modules but this one installed and see if you can still replicate it. I've had to open issues on other NR module that have caused issues like this.

**Comment by skylord123** [comment]
Closing as stale — the thread petered out without a definitive repro, and a few things along the way may have mitigated different paths (external module interference, the "deploy modified flows" case that v0.8.0 addressed by clearing the Matrix client from global storage on shutdown, and possible clock-skew with the initialized-at filter that compares timestamps). If anyone still hits this on a current release, please open a new issue with the Node-RED log around the duplication and we'll dig in.
